var annotated =
[
    [ "FConfig", "interface_f_config.html", "interface_f_config" ],
    [ "<FConfigObserver>", "protocol_f_config_observer-p.html", "protocol_f_config_observer-p" ],
    [ "Flurry", "interface_flurry.html", null ],
    [ "FlurryAdBanner", "interface_flurry_ad_banner.html", "interface_flurry_ad_banner" ],
    [ "<FlurryAdBannerDelegate>", "protocol_flurry_ad_banner_delegate-p.html", "protocol_flurry_ad_banner_delegate-p" ],
    [ "<FlurryAdDelegate>", "protocol_flurry_ad_delegate-p.html", "protocol_flurry_ad_delegate-p" ],
    [ "FlurryAdInterstitial", "interface_flurry_ad_interstitial.html", "interface_flurry_ad_interstitial" ],
    [ "<FlurryAdInterstitialDelegate>", "protocol_flurry_ad_interstitial_delegate-p.html", "protocol_flurry_ad_interstitial_delegate-p" ],
    [ "FlurryAdNative", "interface_flurry_ad_native.html", "interface_flurry_ad_native" ],
    [ "FlurryAdNativeAsset", "interface_flurry_ad_native_asset.html", "interface_flurry_ad_native_asset" ],
    [ "<FlurryAdNativeDelegate>", "protocol_flurry_ad_native_delegate-p.html", "protocol_flurry_ad_native_delegate-p" ],
    [ "FlurryAdNativeStyle", "interface_flurry_ad_native_style.html", "interface_flurry_ad_native_style" ],
    [ "FlurryAds", "interface_flurry_ads.html", null ],
    [ "<FlurryAdStreamDelegate>", "protocol_flurry_ad_stream_delegate-p.html", "protocol_flurry_ad_stream_delegate-p" ],
    [ "FlurryAdTargeting", "interface_flurry_ad_targeting.html", "interface_flurry_ad_targeting" ],
    [ "<FlurryDelegate>", "protocol_flurry_delegate-p.html", "protocol_flurry_delegate-p" ],
    [ "FlurryImageShareParameters", "interface_flurry_image_share_parameters.html", "interface_flurry_image_share_parameters" ],
    [ "FlurrySessionBuilder", "interface_flurry_session_builder.html", "interface_flurry_session_builder" ],
    [ "FlurryTextShareParameters", "interface_flurry_text_share_parameters.html", "interface_flurry_text_share_parameters" ],
    [ "FlurryTumblr", "interface_flurry_tumblr.html", null ],
    [ "<FlurryTumblrDelegate>", "protocol_flurry_tumblr_delegate-p.html", "protocol_flurry_tumblr_delegate-p" ],
    [ "FlurryWatch", "interface_flurry_watch.html", null ],
    [ "<IFlurryTumblrShareParameters>", "protocol_i_flurry_tumblr_share_parameters-p.html", "protocol_i_flurry_tumblr_share_parameters-p" ]
];